### Importação das bibliotecas

In [23]:
import pandas as pd

### Carregamento dos dados

In [24]:
df = pd.read_csv("../data/raw/produtos_raw.csv")

In [25]:
df.head(10)

,name,price,code,actual_category
0,Transponder AIS Maré Magnum,R$ 33122.52,1,ELETRONICOS
1,Transponder Furuno Marlin,R$ 13998.15,2,ELETRONICOS
2,Radar Furuno Pulse Leviathan,R$ 9024.19,3,E L E T R Ô N I C O S
3,Rádio AIS Hydro Tidal Zen,R$ 3381.88,4,Eletrunicos
4,Piloto Automático Furuno Storm,R$ 23669.01,5,Eletronicoz
5,Transponder AIS Vector,R$ 11820.21,6,Eletrunicos
6,Radar AIS Zen,R$ 19518.77,7,eLeTrÔnIcOs
7,GPS AIS Zen,R$ 4984.15,8,E L E T R Ô N I C O S
8,Transponder AIS Titan Pulse,R$ 39705.5,9,Eletronicoz
9,Piloto Automático Simrad Titan Flux Magnum,R$ 32033.04,10,eletrônicos

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             157 non-null    str
 1   price            157 non-null    str
 2   code             157 non-null    int64
 3   actual_category  157 non-null    str
dtypes: int64(1), str(3)
memory usage: 5.0 KB

### Padronização das categorias

In [27]:
df["actual_category"].unique()

<StringArray>
[          'ELETRONICOS', 'E L E T R Ô N I C O S',           'Eletrunicos',
           'Eletronicoz',           'eLeTrÔnIcOs',           'eletrônicos',
           'Eletrônicos',          'Eletroniscos',           'Eletronicos',
           'eletronicos',           'EletrônicoS',           'ELEtRÔNICOS',
             'PROPULSAO',             'Propulção',                  'Prop',
            'Propulssão',             'propulsao',     'P R O P U L S Ã O',
              'Propução',             'propulsão',             'pRoPuLsÃo',
             'Propulçao',             'Propulsam',             'PrOpUlSãO',
             'Ancoragem',             'AnCoRaGeM',             'Encoragem',
            'Ancoraguem',              'Ancorajm',             'AncorageM',
     'A N C O R A G E M',             'ANCORAGEM',             'aNcOrAgEm',
             'Ancorajem',              'Encoragi',             'ancoragem',
             'Ancorajen',             'AncorajeM',             'Ancoragen']
Length: 39, dtype: str

In [28]:
category_map = {
  # ELETRÔNICOS
  "ELETRONICOS":      "eletrônicos",
  "E L E T R Ô N I C O S": "eletrônicos",
  "Eletrunicos":      "eletrônicos",
  "Eletronicoz":      "eletrônicos",
  "eLeTrÔnIcOs":      "eletrônicos",
  "eletrônicos":      "eletrônicos",
  "Eletrônicos":      "eletrônicos",
  "Eletroniscos":     "eletrônicos",
  "Eletronicos":      "eletrônicos",
  "eletronicos":      "eletrônicos",
  "EletrônicoS":      "eletrônicos",
  "ELEtRÔNICOS":      "eletrônicos",

  # PROPULSÃO
  "PROPULSAO":        "propulsão",
  "Propulção":        "propulsão",
  "Prop":             "propulsão",
  "Propulssão":       "propulsão",
  "propulsao":        "propulsão",
  "P R O P U L S Ã O": "propulsão",
  "Propução":         "propulsão",
  "propulsão":        "propulsão",
  "pRoPuLsÃo":        "propulsão",
  "Propulçao":        "propulsão",
  "Propulsam":        "propulsão",
  "PrOpUlSãO":        "propulsão",

  # ANCORAGEM
  "Ancoragem":        "ancoragem",
  "AnCoRaGeM":        "ancoragem",
  "Encoragem":        "ancoragem",
  "Ancoraguem":       "ancoragem",
  "Ancorajm":         "ancoragem",
  "AncorageM":        "ancoragem",
  "A N C O R A G E M": "ancoragem",
  "ANCORAGEM":        "ancoragem",
  "aNcOrAgEm":        "ancoragem",
  "Ancorajem":        "ancoragem",
  "Encoragi":         "ancoragem",
  "ancoragem":        "ancoragem",
  "Ancorajen":        "ancoragem",
  "AncorajeM":        "ancoragem",
  "Ancoragen":        "ancoragem",
}

In [29]:
df["actual_category"] = df["actual_category"].map(category_map)
df["actual_category"].unique()

<StringArray>
['eletrônicos', 'propulsão', 'ancoragem']
Length: 3, dtype: str

In [30]:
df.sample(10)

,name,price,code,actual_category
134,Corrente Delta Boost,R$ 3266.21,129,ancoragem
21,Transponder Furuno Force Ion,R$ 39452.86,22,eletrônicos
2,Radar Furuno Pulse Leviathan,R$ 9024.19,3,eletrônicos
31,Sonda AIS Impulse Oceanic Zenith,R$ 12502.46,32,eletrônicos
61,Motor Diesel Honda Prime 84HP,R$ 28018.63,61,propulsão
109,Âncora Danforth Nitro Titan Vox,R$ 4384.87,106,ancoragem
104,Cabo de Nylon Delta Vortex,R$ 463.4,101,ancoragem
76,Motor de Popa Torqeedo Core Hydra Flux 162HP,R$ 143159.93,73,propulsão
7,GPS AIS Zen,R$ 4984.15,8,eletrônicos
118,Cabo de Nylon Delta Force Magnum Leviathan,R$ 830.59,115,ancoragem

### Convertendo preço para o tipo numerico

In [31]:
df['price'] = df['price'].str.replace('R$', '').str.strip()
df['price'] = pd.to_numeric(df['price'])

In [32]:
df.sample(10)

,name,price,code,actual_category
135,Boia de Arqueamento Delta Zen Boost Vortex,4144.09,130,ancoragem
149,Boia de Arqueamento Bruce Barracuda,2214.14,144,ancoragem
60,Motor de Popa Honda Velocity Drift 258HP,108751.09,60,propulsão
74,Motor Elétrico Torqeedo Pulse 300HP,130174.06,71,propulsão
125,Âncora Danforth Oceanic Helix Flux,3694.27,121,ancoragem
140,Cabo de Nylon Danforth Titan Poseidon,1644.51,135,ancoragem
6,Radar AIS Zen,19518.77,7,eletrônicos
24,Rádio Lowrance Nitro Thrust Barracuda,12126.46,25,eletrônicos
2,Radar Furuno Pulse Leviathan,9024.19,3,eletrônicos
105,Cabo de Nylon Bruce Nexus,832.02,102,ancoragem

In [33]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             157 non-null    str
 1   price            157 non-null    float64
 2   code             157 non-null    int64
 3   actual_category  157 non-null    str
dtypes: float64(1), int64(1), str(2)
memory usage: 5.0 KB

### Verificar duplicatas

In [34]:
df.duplicated().sum()

np.int64(7)

In [35]:
df[df.duplicated()]

                                       name      price  code actual_category
37             GPS Lowrance Evo Storm Drift    6067.71    37     eletrônicos
63        Motor Diesel Yanmar Velocity 37HP  102221.97    62       propulsão
64        Motor Diesel Yanmar Velocity 37HP  102221.97    62       propulsão
65        Motor Diesel Yanmar Velocity 37HP  102221.97    62       propulsão
132  Cabo de Nylon Delta Velocity Core Mako    1549.35   127       ancoragem
150         Boia de Arqueamento Delta Nexus    4349.86   145       ancoragem
151         Boia de Arqueamento Delta Nexus    4349.86   145       ancoragem

In [36]:
df[df["code"].isin([37, 62, 127, 145])].sort_values(by="code")

                                       name      price  code actual_category
36             GPS Lowrance Evo Storm Drift    6067.71    37     eletrônicos
37             GPS Lowrance Evo Storm Drift    6067.71    37     eletrônicos
62        Motor Diesel Yanmar Velocity 37HP  102221.97    62       propulsão
63        Motor Diesel Yanmar Velocity 37HP  102221.97    62       propulsão
64        Motor Diesel Yanmar Velocity 37HP  102221.97    62       propulsão
65        Motor Diesel Yanmar Velocity 37HP  102221.97    62       propulsão
131  Cabo de Nylon Delta Velocity Core Mako    1549.35   127       ancoragem
132  Cabo de Nylon Delta Velocity Core Mako    1549.35   127       ancoragem
124         Boia de Arqueamento Delta Nexus    4349.86   145       ancoragem
150         Boia de Arqueamento Delta Nexus    4349.86   145       ancoragem
151         Boia de Arqueamento Delta Nexus    4349.86   145       ancoragem

In [37]:
df = df.drop_duplicates(subset='code', keep='first')

In [38]:
df.duplicated().sum()

np.int64(0)

In [39]:
df[df["code"].isin([37, 62, 127, 145])].sort_values(by="code")

                                       name      price  code actual_category
36             GPS Lowrance Evo Storm Drift    6067.71    37     eletrônicos
62        Motor Diesel Yanmar Velocity 37HP  102221.97    62       propulsão
131  Cabo de Nylon Delta Velocity Core Mako    1549.35   127       ancoragem
124         Boia de Arqueamento Delta Nexus    4349.86   145       ancoragem

In [40]:
df = df.set_index("code")

In [41]:
df.head(5)

                                name     price actual_category
code
1        Transponder AIS Maré Magnum  33122.52     eletrônicos
2          Transponder Furuno Marlin  13998.15     eletrônicos
3       Radar Furuno Pulse Leviathan   9024.19     eletrônicos
4          Rádio AIS Hydro Tidal Zen   3381.88     eletrônicos
5     Piloto Automático Furuno Storm  23669.01     eletrônicos

In [42]:
df.info()

<class 'pandas.DataFrame'>
Index: 150 entries, 1 to 150
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             150 non-null    str
 1   price            150 non-null    float64
 2   actual_category  150 non-null    str
dtypes: float64(1), str(2)
memory usage: 4.7 KB

In [43]:
df.head(10)

                                            name     price actual_category
code
1                    Transponder AIS Maré Magnum  33122.52     eletrônicos
2                      Transponder Furuno Marlin  13998.15     eletrônicos
3                   Radar Furuno Pulse Leviathan   9024.19     eletrônicos
4                      Rádio AIS Hydro Tidal Zen   3381.88     eletrônicos
5                 Piloto Automático Furuno Storm  23669.01     eletrônicos
6                         Transponder AIS Vector  11820.21     eletrônicos
7                                  Radar AIS Zen  19518.77     eletrônicos
8                                    GPS AIS Zen   4984.15     eletrônicos
9                    Transponder AIS Titan Pulse  39705.50     eletrônicos
10    Piloto Automático Simrad Titan Flux Magnum  32033.04     eletrônicos

In [44]:
df.to_csv('../data/processed/produtos_processed.csv', index=True)