### Importação das bibliotecas

In [44]:
import pandas as pd
import matplotlib.pyplot as plt

### Carregamento dos dados

In [45]:
df = pd.read_csv("../data/produtos_raw.csv")

In [46]:
df.head(10)

,name,price,code,actual_category
0,Transponder AIS Maré Magnum,R$ 33122.52,1,ELETRONICOS
1,Transponder Furuno Marlin,R$ 13998.15,2,ELETRONICOS
2,Radar Furuno Pulse Leviathan,R$ 9024.19,3,E L E T R Ô N I C O S
3,Rádio AIS Hydro Tidal Zen,R$ 3381.88,4,Eletrunicos
4,Piloto Automático Furuno Storm,R$ 23669.01,5,Eletronicoz
5,Transponder AIS Vector,R$ 11820.21,6,Eletrunicos
6,Radar AIS Zen,R$ 19518.77,7,eLeTrÔnIcOs
7,GPS AIS Zen,R$ 4984.15,8,E L E T R Ô N I C O S
8,Transponder AIS Titan Pulse,R$ 39705.5,9,Eletronicoz
9,Piloto Automático Simrad Titan Flux Magnum,R$ 32033.04,10,eletrônicos

In [47]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             157 non-null    str
 1   price            157 non-null    str
 2   code             157 non-null    int64
 3   actual_category  157 non-null    str
dtypes: int64(1), str(3)
memory usage: 5.0 KB

### Padronização das categorias

In [48]:
df["actual_category"].unique()

<StringArray>
[          'ELETRONICOS', 'E L E T R Ô N I C O S',           'Eletrunicos',
           'Eletronicoz',           'eLeTrÔnIcOs',           'eletrônicos',
           'Eletrônicos',          'Eletroniscos',           'Eletronicos',
           'eletronicos',           'EletrônicoS',           'ELEtRÔNICOS',
             'PROPULSAO',             'Propulção',                  'Prop',
            'Propulssão',             'propulsao',     'P R O P U L S Ã O',
              'Propução',             'propulsão',             'pRoPuLsÃo',
             'Propulçao',             'Propulsam',             'PrOpUlSãO',
             'Ancoragem',             'AnCoRaGeM',             'Encoragem',
            'Ancoraguem',              'Ancorajm',             'AncorageM',
     'A N C O R A G E M',             'ANCORAGEM',             'aNcOrAgEm',
             'Ancorajem',              'Encoragi',             'ancoragem',
             'Ancorajen',             'AncorajeM',             'Ancoragen']
Length: 39, dtype: str

In [49]:
category_map = {
  # ELETRÔNICOS
  "ELETRONICOS":      "eletronicos",
  "E L E T R Ô N I C O S": "eletronicos",
  "Eletrunicos":      "eletronicos",
  "Eletronicoz":      "eletronicos",
  "eLeTrÔnIcOs":      "eletronicos",
  "eletrônicos":      "eletronicos",
  "Eletrônicos":      "eletronicos",
  "Eletroniscos":     "eletronicos",
  "Eletronicos":      "eletronicos",
  "eletronicos":      "eletronicos",
  "EletrônicoS":      "eletronicos",
  "ELEtRÔNICOS":      "eletronicos",

  # PROPULSÃO
  "PROPULSAO":        "propulsao",
  "Propulção":        "propulsao",
  "Prop":             "propulsao",
  "Propulssão":       "propulsao",
  "propulsao":        "propulsao",
  "P R O P U L S Ã O": "propulsao",
  "Propução":         "propulsao",
  "propulsão":        "propulsao",
  "pRoPuLsÃo":        "propulsao",
  "Propulçao":        "propulsao",
  "Propulsam":        "propulsao",
  "PrOpUlSãO":        "propulsao",

  # ANCORAGEM
  "Ancoragem":        "ancoragem",
  "AnCoRaGeM":        "ancoragem",
  "Encoragem":        "ancoragem",
  "Ancoraguem":       "ancoragem",
  "Ancorajm":         "ancoragem",
  "AncorageM":        "ancoragem",
  "A N C O R A G E M": "ancoragem",
  "ANCORAGEM":        "ancoragem",
  "aNcOrAgEm":        "ancoragem",
  "Ancorajem":        "ancoragem",
  "Encoragi":         "ancoragem",
  "ancoragem":        "ancoragem",
  "Ancorajen":        "ancoragem",
  "AncorajeM":        "ancoragem",
  "Ancoragen":        "ancoragem",
}

In [50]:
df["actual_category"] = df["actual_category"].map(category_map)
df["actual_category"].unique()

<StringArray>
['eletronicos', 'propulsao', 'ancoragem']
Length: 3, dtype: str

In [51]:
df.sample(10)

,name,price,code,actual_category
11,GPS AIS Drift Flux Vox,R$ 2726.18,12,eletronicos
113,Corrente Bruce Current,R$ 2495.51,110,ancoragem
75,Motor de Popa Volvo Hydro Dash 256HP,R$ 99664.64,72,propulsao
109,Âncora Danforth Nitro Titan Vox,R$ 4384.87,106,ancoragem
3,Rádio AIS Hydro Tidal Zen,R$ 3381.88,4,eletronicos
128,Corrente Delta Axis,R$ 3769.93,124,ancoragem
107,Cabo de Nylon Delta Zen Vortex Storm,R$ 3713.02,104,ancoragem
36,GPS Lowrance Evo Storm Drift,R$ 6067.71,37,eletronicos
81,Motor Elétrico Honda Mako Axis 131HP,R$ 121761.56,78,propulsao
94,Motor Elétrico Tohatsu Zenith Oceanic 113HP,R$ 134886.02,91,propulsao

### Convertendo preço para o tipo numerico

In [52]:
df['price'] = df['price'].str.replace('R$', '').str.strip()
df['price'] = pd.to_numeric(df['price'])

In [53]:
df.sample(10)

,name,price,code,actual_category
110,Boia de Arqueamento Bruce Tidal Marlin,1513.38,107,ancoragem
18,Sonda Lowrance Tidal Storm Vox,16432.35,19,eletronicos
119,Cabo de Nylon Delta Velocity Oceanic Abyss,2575.52,116,ancoragem
69,Motor de Popa Tohatsu Poseidon Helix Prime 135HP,12571.63,66,propulsao
150,Boia de Arqueamento Delta Nexus,4349.86,145,ancoragem
32,Transponder Garmin Drift Vortex Marlin,6715.77,33,eletronicos
13,Rádio Furuno Zen Swift,35811.08,14,eletronicos
44,GPS Simrad Zen Hydra Peak,10806.84,44,eletronicos
36,GPS Lowrance Evo Storm Drift,6067.71,37,eletronicos
30,Transponder Furuno Pulse Axis,8283.11,31,eletronicos

In [54]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             157 non-null    str
 1   price            157 non-null    float64
 2   code             157 non-null    int64
 3   actual_category  157 non-null    str
dtypes: float64(1), int64(1), str(2)
memory usage: 5.0 KB

### Verificar duplicatas

In [55]:
df.duplicated().sum()

np.int64(7)

In [56]:
df[df.duplicated()]

                                       name      price  code actual_category
37             GPS Lowrance Evo Storm Drift    6067.71    37     eletronicos
63        Motor Diesel Yanmar Velocity 37HP  102221.97    62       propulsao
64        Motor Diesel Yanmar Velocity 37HP  102221.97    62       propulsao
65        Motor Diesel Yanmar Velocity 37HP  102221.97    62       propulsao
132  Cabo de Nylon Delta Velocity Core Mako    1549.35   127       ancoragem
150         Boia de Arqueamento Delta Nexus    4349.86   145       ancoragem
151         Boia de Arqueamento Delta Nexus    4349.86   145       ancoragem

In [67]:
df[df["code"].isin([37, 62, 127, 145])].sort_values(by="code")

                                       name      price  code actual_category
36             GPS Lowrance Evo Storm Drift    6067.71    37     eletronicos
37             GPS Lowrance Evo Storm Drift    6067.71    37     eletronicos
62        Motor Diesel Yanmar Velocity 37HP  102221.97    62       propulsao
63        Motor Diesel Yanmar Velocity 37HP  102221.97    62       propulsao
64        Motor Diesel Yanmar Velocity 37HP  102221.97    62       propulsao
65        Motor Diesel Yanmar Velocity 37HP  102221.97    62       propulsao
131  Cabo de Nylon Delta Velocity Core Mako    1549.35   127       ancoragem
132  Cabo de Nylon Delta Velocity Core Mako    1549.35   127       ancoragem
124         Boia de Arqueamento Delta Nexus    4349.86   145       ancoragem
150         Boia de Arqueamento Delta Nexus    4349.86   145       ancoragem
151         Boia de Arqueamento Delta Nexus    4349.86   145       ancoragem

In [69]:
df = df.drop_duplicates(subset='code', keep='first')

In [70]:
df.duplicated().sum()

np.int64(0)

In [71]:
df[df["code"].isin([37, 62, 127, 145])].sort_values(by="code")

                                       name      price  code actual_category
36             GPS Lowrance Evo Storm Drift    6067.71    37     eletronicos
62        Motor Diesel Yanmar Velocity 37HP  102221.97    62       propulsao
131  Cabo de Nylon Delta Velocity Core Mako    1549.35   127       ancoragem
124         Boia de Arqueamento Delta Nexus    4349.86   145       ancoragem

In [72]:
df.info()

<class 'pandas.DataFrame'>
Index: 150 entries, 0 to 156
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             150 non-null    str
 1   price            150 non-null    float64
 2   code             150 non-null    int64
 3   actual_category  150 non-null    str
dtypes: float64(1), int64(1), str(2)
memory usage: 5.9 KB

In [ ]:
df.sample(20)

,name,price,code,actual_category
85,Motor Elétrico Volvo Nautic Vox 118HP,51634.04,82,propulsao
102,Motor Elétrico Honda Flux Ultra 273HP,107266.66,99,propulsao
140,Cabo de Nylon Danforth Titan Poseidon,1644.51,135,ancoragem
141,Cabo de Nylon Bruce Flux Hydro,1973.50,136,ancoragem
19,Radar AIS Marlin,30833.44,20,eletronicos
148,Âncora Delta Hydra Kraken Velocity,4436.43,143,ancoragem
8,Transponder AIS Titan Pulse,39705.50,9,eletronicos
46,Sonda AIS Magnum Boost,4983.77,46,eletronicos
24,Rádio Lowrance Nitro Thrust Barracuda,12126.46,25,eletronicos
7,GPS AIS Zen,4984.15,8,eletronicos
48,GPS Furuno Magnum Drift,14736.35,48,eletronicos
23,GPS AIS Orca Marlin Velocity,23232.18,24,eletronicos
20,GPS AIS Nautic Thrust,8734.56,21,eletronicos
1,Transponder Furuno Marlin,13998.15,2,eletronicos
73,Motor Diesel Parsun Boost Helix Velocity 146HP,34355.43,70,propulsao
127,Cabo de Nylon Danforth Orca Aero,2777.07,123,ancoragem
54,Motor de Popa Yamaha Evo Dash 155HP,121534.82,54,propulsao
134,Corrente Delta Boost,3266.21,129,ancoragem
78,Motor Diesel Volvo Flow Leviathan Maré 187HP,32768.38,75,propulsao
89,Motor Diesel Volvo Helix Evo Force 144HP,93523.13,86,propulsao