### Importação das bibliotecas

In [1]:
import pandas as pd

### Carregamento dos dados

In [2]:
df = pd.read_csv("../data/raw/produtos_raw.csv")

In [3]:
df.head(10)

,name,price,code,actual_category
0,Transponder AIS Maré Magnum,R$ 33122.52,1,ELETRONICOS
1,Transponder Furuno Marlin,R$ 13998.15,2,ELETRONICOS
2,Radar Furuno Pulse Leviathan,R$ 9024.19,3,E L E T R Ô N I C O S
3,Rádio AIS Hydro Tidal Zen,R$ 3381.88,4,Eletrunicos
4,Piloto Automático Furuno Storm,R$ 23669.01,5,Eletronicoz
5,Transponder AIS Vector,R$ 11820.21,6,Eletrunicos
6,Radar AIS Zen,R$ 19518.77,7,eLeTrÔnIcOs
7,GPS AIS Zen,R$ 4984.15,8,E L E T R Ô N I C O S
8,Transponder AIS Titan Pulse,R$ 39705.5,9,Eletronicoz
9,Piloto Automático Simrad Titan Flux Magnum,R$ 32033.04,10,eletrônicos

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             157 non-null    str
 1   price            157 non-null    str
 2   code             157 non-null    int64
 3   actual_category  157 non-null    str
dtypes: int64(1), str(3)
memory usage: 5.0 KB

### Padronização das categorias

In [5]:
df["actual_category"].unique()

<StringArray>
[          'ELETRONICOS', 'E L E T R Ô N I C O S',           'Eletrunicos',
           'Eletronicoz',           'eLeTrÔnIcOs',           'eletrônicos',
           'Eletrônicos',          'Eletroniscos',           'Eletronicos',
           'eletronicos',           'EletrônicoS',           'ELEtRÔNICOS',
             'PROPULSAO',             'Propulção',                  'Prop',
            'Propulssão',             'propulsao',     'P R O P U L S Ã O',
              'Propução',             'propulsão',             'pRoPuLsÃo',
             'Propulçao',             'Propulsam',             'PrOpUlSãO',
             'Ancoragem',             'AnCoRaGeM',             'Encoragem',
            'Ancoraguem',              'Ancorajm',             'AncorageM',
     'A N C O R A G E M',             'ANCORAGEM',             'aNcOrAgEm',
             'Ancorajem',              'Encoragi',             'ancoragem',
             'Ancorajen',             'AncorajeM',             'Ancoragen']
Length: 39, dtype: str

In [6]:
category_map = {
  # ELETRÔNICOS
  "ELETRONICOS":      "eletrônicos",
  "E L E T R Ô N I C O S": "eletrônicos",
  "Eletrunicos":      "eletrônicos",
  "Eletronicoz":      "eletrônicos",
  "eLeTrÔnIcOs":      "eletrônicos",
  "eletrônicos":      "eletrônicos",
  "Eletrônicos":      "eletrônicos",
  "Eletroniscos":     "eletrônicos",
  "Eletronicos":      "eletrônicos",
  "eletronicos":      "eletrônicos",
  "EletrônicoS":      "eletrônicos",
  "ELEtRÔNICOS":      "eletrônicos",

  # PROPULSÃO
  "PROPULSAO":        "propulsão",
  "Propulção":        "propulsão",
  "Prop":             "propulsão",
  "Propulssão":       "propulsão",
  "propulsao":        "propulsão",
  "P R O P U L S Ã O": "propulsão",
  "Propução":         "propulsão",
  "propulsão":        "propulsão",
  "pRoPuLsÃo":        "propulsão",
  "Propulçao":        "propulsão",
  "Propulsam":        "propulsão",
  "PrOpUlSãO":        "propulsão",

  # ANCORAGEM
  "Ancoragem":        "ancoragem",
  "AnCoRaGeM":        "ancoragem",
  "Encoragem":        "ancoragem",
  "Ancoraguem":       "ancoragem",
  "Ancorajm":         "ancoragem",
  "AncorageM":        "ancoragem",
  "A N C O R A G E M": "ancoragem",
  "ANCORAGEM":        "ancoragem",
  "aNcOrAgEm":        "ancoragem",
  "Ancorajem":        "ancoragem",
  "Encoragi":         "ancoragem",
  "ancoragem":        "ancoragem",
  "Ancorajen":        "ancoragem",
  "AncorajeM":        "ancoragem",
  "Ancoragen":        "ancoragem",
}

In [7]:
df["actual_category"] = df["actual_category"].map(category_map)
df["actual_category"].unique()

<StringArray>
['eletrônicos', 'propulsão', 'ancoragem']
Length: 3, dtype: str

In [8]:
df.sample(10)

,name,price,code,actual_category
106,Âncora Delta Swift,R$ 1789.19,103,ancoragem
12,Radar Simrad Boost,R$ 7747.1,13,eletrônicos
77,Motor de Popa Honda Torque 228HP,R$ 86558.56,74,propulsão
81,Motor Elétrico Honda Mako Axis 131HP,R$ 121761.56,78,propulsão
38,Rádio AIS Force,R$ 26461.14,38,eletrônicos
80,Motor Diesel Tohatsu Vector 197HP,R$ 44704.67,77,propulsão
54,Motor de Popa Yamaha Evo Dash 155HP,R$ 121534.82,54,propulsão
101,Motor Diesel Parsun Velocity Abyss Orca 235HP,R$ 79361.13,98,propulsão
92,Motor Elétrico Yamaha Orca Storm Zenith 11HP,R$ 78678.05,89,propulsão
126,Corrente Danforth Zenith Oceanic Torque,R$ 1322.47,122,ancoragem

### Convertendo preço para o tipo numerico

In [9]:
df['price'] = df['price'].str.replace('R$', '').str.strip()
df['price'] = pd.to_numeric(df['price'])

In [10]:
df.sample(10)

,name,price,code,actual_category
113,Corrente Bruce Current,2495.51,110,ancoragem
122,Âncora Bruce Aqua,3255.82,119,ancoragem
63,Motor Diesel Yanmar Velocity 37HP,102221.97,62,propulsão
156,Cabo de Nylon Danforth Magnum Vox,1645.66,150,ancoragem
111,Boia de Arqueamento Bruce Titan,3345.56,108,ancoragem
87,Motor de Popa Torqeedo Zenith Peak Thrust 212HP,43423.88,84,propulsão
34,Radar Furuno Swift,11005.53,35,eletrônicos
54,Motor de Popa Yamaha Evo Dash 155HP,121534.82,54,propulsão
131,Cabo de Nylon Delta Velocity Core Mako,1549.35,127,ancoragem
33,Transponder AIS Helix Torque,4917.53,34,eletrônicos

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             157 non-null    str
 1   price            157 non-null    float64
 2   code             157 non-null    int64
 3   actual_category  157 non-null    str
dtypes: float64(1), int64(1), str(2)
memory usage: 5.0 KB

### Verificar duplicatas

In [12]:
df.duplicated().sum()

np.int64(7)

In [13]:
df[df.duplicated()]

                                       name      price  code actual_category
37             GPS Lowrance Evo Storm Drift    6067.71    37     eletrônicos
63        Motor Diesel Yanmar Velocity 37HP  102221.97    62       propulsão
64        Motor Diesel Yanmar Velocity 37HP  102221.97    62       propulsão
65        Motor Diesel Yanmar Velocity 37HP  102221.97    62       propulsão
132  Cabo de Nylon Delta Velocity Core Mako    1549.35   127       ancoragem
150         Boia de Arqueamento Delta Nexus    4349.86   145       ancoragem
151         Boia de Arqueamento Delta Nexus    4349.86   145       ancoragem

In [14]:
df[df["code"].isin([37, 62, 127, 145])].sort_values(by="code")

                                       name      price  code actual_category
36             GPS Lowrance Evo Storm Drift    6067.71    37     eletrônicos
37             GPS Lowrance Evo Storm Drift    6067.71    37     eletrônicos
62        Motor Diesel Yanmar Velocity 37HP  102221.97    62       propulsão
63        Motor Diesel Yanmar Velocity 37HP  102221.97    62       propulsão
64        Motor Diesel Yanmar Velocity 37HP  102221.97    62       propulsão
65        Motor Diesel Yanmar Velocity 37HP  102221.97    62       propulsão
131  Cabo de Nylon Delta Velocity Core Mako    1549.35   127       ancoragem
132  Cabo de Nylon Delta Velocity Core Mako    1549.35   127       ancoragem
124         Boia de Arqueamento Delta Nexus    4349.86   145       ancoragem
150         Boia de Arqueamento Delta Nexus    4349.86   145       ancoragem
151         Boia de Arqueamento Delta Nexus    4349.86   145       ancoragem

In [15]:
df = df.drop_duplicates(subset='code', keep='first')

In [16]:
df.duplicated().sum()

np.int64(0)

In [17]:
df[df["code"].isin([37, 62, 127, 145])].sort_values(by="code")

                                       name      price  code actual_category
36             GPS Lowrance Evo Storm Drift    6067.71    37     eletrônicos
62        Motor Diesel Yanmar Velocity 37HP  102221.97    62       propulsão
131  Cabo de Nylon Delta Velocity Core Mako    1549.35   127       ancoragem
124         Boia de Arqueamento Delta Nexus    4349.86   145       ancoragem

In [18]:
df.info()

<class 'pandas.DataFrame'>
Index: 150 entries, 0 to 156
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             150 non-null    str
 1   price            150 non-null    float64
 2   code             150 non-null    int64
 3   actual_category  150 non-null    str
dtypes: float64(1), int64(1), str(2)
memory usage: 5.9 KB

In [19]:
df.sample(20)

,name,price,code,actual_category
114,Boia de Arqueamento Danforth Aero Dash,4285.23,111,ancoragem
87,Motor de Popa Torqeedo Zenith Peak Thrust 212HP,43423.88,84,propulsão
39,GPS Furuno Vector,29632.83,39,eletrônicos
76,Motor de Popa Torqeedo Core Hydra Flux 162HP,143159.93,73,propulsão
92,Motor Elétrico Yamaha Orca Storm Zenith 11HP,78678.05,89,propulsão
111,Boia de Arqueamento Bruce Titan,3345.56,108,ancoragem
75,Motor de Popa Volvo Hydro Dash 256HP,99664.64,72,propulsão
10,GPS Furuno Swift Leviathan Poseidon,36231.91,11,eletrônicos
69,Motor de Popa Tohatsu Poseidon Helix Prime 135HP,12571.63,66,propulsão
85,Motor Elétrico Volvo Nautic Vox 118HP,51634.04,82,propulsão
49,Sonda Furuno Swift,13264.25,49,eletrônicos
126,Corrente Danforth Zenith Oceanic Torque,1322.47,122,ancoragem
148,Âncora Delta Hydra Kraken Velocity,4436.43,143,ancoragem
129,Cabo de Nylon Danforth Kinetic,3402.07,125,ancoragem
115,Corrente Danforth Tidal,2180.95,112,ancoragem
138,Âncora Bruce Core Pulse,1892.72,133,ancoragem
105,Cabo de Nylon Bruce Nexus,832.02,102,ancoragem
112,Cabo de Nylon Danforth Evo Aqua Mako,622.70,109,ancoragem
52,Motor Diesel Honda Zen Tidal Mako 26HP,13704.10,52,propulsão
54,Motor de Popa Yamaha Evo Dash 155HP,121534.82,54,propulsão